#7 Написать бизнес логику перехода по короткой ссылке
NoXml/Shortly pull request #12
Opened 2021-07-08 16:25 UTC by shpikich

2021-07-09 09:43 UTC, AlexAntufiev requested changes

2021-07-09 09:43 UTC, AlexAntufiev commented on src/main/java/ru/shortly/controller/schemas/NewLink.java
> +    public NewLink(@JsonProperty("url") String url) {
это чит) нужен публичный статический метод, который возвращает билдер это объекта, у которого вызываем ешь методы по построению объекта, а потом метод билд

2021-07-09 09:43 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +    public UrlRepository(HashMap<String, NewLink> urls) {
нам не нужно знать и париться снаружи, что репозиторий построен на hashmap, поэтому конструктор должен быть без аргументов, но инициализация поля именно в конструкторе

2021-07-09 09:43 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +        String alphabet = "abcdefghijklmnopqrstuvwxyz0123456789";
это нужно вынести в статическую переменную(один раз создаться, не будет меняться и удаляться из памяти), а именно с модификаторами private static final. В твоем решение она будет создавать каждый раз при вызове метода

2021-07-09 09:43 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +        char[] charsUrlPath = new char[6];
размер ссылки тоже нужно вынести в статическую переменную, чтобы потом менять и было понятно что это такое, иначе сейчас непонятно что такое 6

2021-07-09 09:43 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +            return urls.get(key);
urls.get(key) и так вернет null, если не будет найден элемент

2021-07-09 09:43 UTC, AlexAntufiev commented on src/test/java/ru/shortly/repository/UrlRepositoryTest.java
> +        assertEquals(newLink, urls.getLink(newKey));
👍

2021-07-09 09:43 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +            putLink(newLink, newKey);
стоп, если у тебя уже есть ключ в мапе, то мы опять запускаем функцию и так до бесконечности - это вызовет ошибку Stack overflow exception)
давай если есть такой же ключ, то кидать исключение IllegalArgument Exception мол ключ уже сохранен

2021-07-10 09:48 UTC, shpikich commented on src/test/java/ru/shortly/repository/UrlRepositoryTest.java
> +    }
Написал тест для проверки работы метода putLink в случае, когда ключ уже есть в мапе

2021-07-10 18:24 UTC, AlexAntufiev requested changes
Теперь нужно связать controller и repository
Посмотри как это сделано в EDATECH

2021-07-10 18:24 UTC, AlexAntufiev commented on src/test/java/ru/shortly/repository/UrlRepositoryTest.java
> +    }
тесты лишними не бывают)

2021-07-10 18:24 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +    public final HashMap<String, NewLink> urls;
private

2021-07-10 18:24 UTC, AlexAntufiev commented on src/main/java/ru/shortly/repository/UrlRepository.java
> +        Random random = new Random();
еще не заметил этот момент. Чтобы уменьшить количество конфликтов, нужно использовать один и тот же объект во всех вызовах этого метода

2021-07-19 18:09 UTC, AlexAntufiev requested changes

2021-07-19 18:09 UTC, AlexAntufiev commented on src/test/java/ru/shortly/controller/LinkControllerTest.java
>      private MockMvc mvc;
в тесте shouldProcessPostRequest нужно проверять, что ссылка присутствует и начинается с "http://localhost:80/"

2021-07-19 18:09 UTC, AlexAntufiev commented on src/test/java/ru/shortly/controller/LinkControllerTest.java
> +class LinkControllerTest {
Это тесты, которые тестируют твой сервис без знаний внутренностей и они хорошие: один раз написал и забыл, сколько угодно создавать классы, меняй реализацию или переписывать не надо

2021-07-19 18:09 UTC, AlexAntufiev commented on src/test/java/ru/shortly/repository/UrlRepositoryTest.java
> +class UrlRepositoryTest {
это тесты, которые тестируют конкретную реализацию, то есть через мапу

2021-07-19 18:09 UTC, AlexAntufiev commented on src/test/java/ru/shortly/repository/UrlRepositoryTest.java
> +@AutoConfigureMockMvc
мокМвс здесь не должно быть

2021-07-19 18:09 UTC, AlexAntufiev commented on src/test/java/ru/shortly/repository/UrlRepositoryTest.java
> +    UrlRepository urls = new UrlRepository();
private final

2021-07-21 09:43 UTC, AlexAntufiev approved these changes

2021-07-21 12:05 UTC, merged