#16 Добавить аннотации JSR-303
NoXml/Shortly pull request #17
Opened 2021-07-29 17:29 UTC by shpikich

2021-07-29 22:00 UTC, AlexAntufiev requested changes

2021-07-29 22:00 UTC, AlexAntufiev commented on build.gradle
> +            name: 'spring-boot-starter-validation', version: '2.5.3'
версию нужно убрать, она тянется из плагина выше 
```
plugins {
    id 'org.springframework.boot' version '2.5.1'
}
```
если хочешь версию 2.5.3, то можешь ее там обновить

```
implementation group: 'org.springframework.boot',
             name: 'spring-boot-starter-validation', version: '2.5.3'
``` 
и 
`implementation'org.springframework.boot':spring-boot-starter-validation:2.5.3'` 
тоже самое

2021-07-29 22:00 UTC, AlexAntufiev commented on src/main/java/ru/shortly/controller/LinkController.java
>                      .withMessage("Parameter 'url' must be not blank")
а сообщение надо проставлять из errors, там по-любому какой-то метод get есть

2021-07-30 09:01 UTC, shpikich commented on src/main/java/ru/shortly/controller/LinkController.java
>                      .withMessage("Parameter 'url' must be not blank")
У errors нет методов, возвращающих значение типа String, поэтому решил сделать через String.valueof()

2021-07-31 20:33 UTC, AlexAntufiev commented on src/main/java/ru/shortly/controller/LinkController.java
>                      .withMessage("Parameter 'url' must be not blank")
сори, не показал как это нужно сделать, добавь такой класс и посмотри какой будет ответ
`@ControllerAdvice
public class RestResponseEntityExceptionHandler 
  extends ResponseEntityExceptionHandler {

    @ResponseStatus(HttpStatus.BAD_REQUEST)
@ExceptionHandler(MethodArgumentNotValidException.class)
public Map<String, String> handleValidationExceptions(
  MethodArgumentNotValidException ex) {
    Map<String, String> errors = new HashMap<>();
    ex.getBindingResult().getAllErrors().forEach((error) -> {
        String fieldName = ((FieldError) error).getField();
        String errorMessage = error.getDefaultMessage();
        errors.put(fieldName, errorMessage);
    });
    return errors;
}
}`

2021-07-31 20:35 UTC, AlexAntufiev requested changes
нужно еще сделать git fetch + git rebase на origin/main

2021-08-18 08:10 UTC, AlexAntufiev commented on src/main/java/ru/shortly/controller/RestResponseEntityExceptionHandler.java
> +@RestControllerAdvice
в этом была проблема, я тупанул) сейчас даже не думай что это такое, лютая хуйня))

2021-08-18 08:11 UTC, AlexAntufiev approved these changes

2021-08-18 08:35 UTC, merged